<?php

namespace TaskPlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
//        $queryTest = $em->createQuery('
//          SELECT u FROM TaskPlannerBundle:User u, TaskPlannerBundle:Task t LEFT JOIN t.user
//        ');
//        $res = $queryTest->getResult();
//        dump($res);
}
